import type {MysteryBoxDefinition, MysteryBoxLoot} from './types.js';

// ── Mystery Boxes ──

export const MYSTERY_BOXES: MysteryBoxDefinition[] = [
    {
        id: 'BOX_BRONZE',
        name: 'ブロンズボックス',
        emoji: '📦',
        description: 'チップや消耗品が入ったお手頃ボックス',
        price: 3_000n,
        category: 'mystery',
        dailyEligible: true,
        giftable: true,
        sourceHint: '/shop ミステリーで購入',
        lootTable: [
            {type: 'chips', chipsMin: 500n, chipsMax: 1_500n, rarity: 'common', weight: 50},
            {type: 'item', itemId: 'MISSION_REROLL', rarity: 'uncommon', weight: 10},
            {type: 'item', itemId: 'WORK_COOLDOWN_SKIP', rarity: 'uncommon', weight: 10},
            {type: 'item', itemId: 'DAILY_BOOST', rarity: 'uncommon', weight: 5},
            {type: 'item', itemId: 'XP_BOOSTER', rarity: 'rare', weight: 7},
            {type: 'item', itemId: 'STREAK_SHIELD', rarity: 'rare', weight: 5},
            {type: 'chips', chipsMin: 2_000n, chipsMax: 3_000n, rarity: 'rare', weight: 10},
            {type: 'item', itemId: 'BADGE_FLAME', rarity: 'epic', weight: 3},
        ],
    },
    {
        id: 'BOX_SILVER',
        name: 'シルバーボックス',
        emoji: '🎁',
        description: 'バフやコスメが出やすい上質ボックス',
        price: 15_000n,
        category: 'mystery',
        dailyEligible: true,
        giftable: true,
        sourceHint: '/shop ミステリーで購入',
        lootTable: [
            {type: 'chips', chipsMin: 5_000n, chipsMax: 10_000n, rarity: 'common', weight: 40},
            {type: 'item', itemId: 'XP_BOOSTER', rarity: 'uncommon', weight: 10},
            {type: 'item', itemId: 'INTEREST_BOOSTER', rarity: 'uncommon', weight: 8},
            {type: 'item', itemId: 'LUCKY_CHARM', rarity: 'uncommon', weight: 7},
            {type: 'item', itemId: 'TITLE_HIGH_ROLLER', rarity: 'rare', weight: 5},
            {type: 'item', itemId: 'TITLE_LUCKY_STAR', rarity: 'rare', weight: 5},
            {type: 'item', itemId: 'BADGE_DIAMOND', rarity: 'rare', weight: 3},
            {type: 'chips', chipsMin: 15_000n, chipsMax: 20_000n, rarity: 'epic', weight: 10},
            {type: 'item', itemId: 'VIP_PASS', rarity: 'epic', weight: 5},
            {type: 'item', itemId: 'SAFETY_NET', rarity: 'epic', weight: 5},
            {type: 'item', itemId: 'MISSION_SLOT_PLUS', rarity: 'legendary', weight: 2},
        ],
    },
    {
        id: 'BOX_GOLD',
        name: 'ゴールドボックス',
        emoji: '✨',
        description: '永続アップグレードも出る最高級ボックス',
        price: 70_000n,
        category: 'mystery',
        giftable: true,
        sourceHint: '/shop ミステリーで購入',
        lootTable: [
            {type: 'chips', chipsMin: 25_000n, chipsMax: 50_000n, rarity: 'common', weight: 30},
            {type: 'item', itemId: 'VIP_PASS', rarity: 'uncommon', weight: 10},
            {type: 'item', itemId: 'INTEREST_BOOSTER', rarity: 'uncommon', weight: 8},
            {type: 'item', itemId: 'SAFETY_NET', rarity: 'uncommon', weight: 7},
            {type: 'item', itemId: 'TITLE_CASINO_KING', rarity: 'rare', weight: 5},
            {type: 'item', itemId: 'TITLE_PHANTOM_THIEF', rarity: 'rare', weight: 5},
            {type: 'item', itemId: 'BADGE_CROWN', rarity: 'rare', weight: 6},
            {type: 'chips', chipsMin: 60_000n, chipsMax: 80_000n, rarity: 'epic', weight: 5},
            {type: 'item', itemId: 'MISSION_SLOT_PLUS', rarity: 'epic', weight: 4},
            {type: 'item', itemId: 'BANK_EXPANSION', rarity: 'epic', weight: 4},
            {type: 'item', itemId: 'GOLDEN_DICE', rarity: 'legendary', weight: 6},
            {type: 'item', itemId: 'CHIP_FOUNTAIN', rarity: 'legendary', weight: 5},
            {type: 'item', itemId: 'VIP_CARD', rarity: 'legendary', weight: 5},
        ],
    },
    {
        id: 'BOX_PLATINUM',
        name: 'プラチナボックス',
        emoji: '👑',
        description: 'クラフト素材＆限定アイテム入り最高級ボックス',
        price: 180_000n,
        category: 'mystery',
        giftable: true,
        lootTable: [
            {type: 'chips', chipsMin: 50_000n, chipsMax: 100_000n, rarity: 'common', weight: 20},
            {type: 'item', itemId: 'LUCKY_CHARM', rarity: 'uncommon', weight: 8},
            {type: 'item', itemId: 'SAFETY_NET', rarity: 'uncommon', weight: 6},
            {type: 'item', itemId: 'VIP_PASS', rarity: 'rare', weight: 8},
            {type: 'item', itemId: 'HEIST_INTEL', rarity: 'rare', weight: 6},
            {type: 'item', itemId: 'LUCKY_TICKET', rarity: 'rare', weight: 6},
            {type: 'chips', chipsMin: 100_000n, chipsMax: 150_000n, rarity: 'epic', weight: 8},
            {type: 'item', itemId: 'BANK_EXPANSION', rarity: 'epic', weight: 5},
            {type: 'item', itemId: 'HEIST_VAULT', rarity: 'epic', weight: 4},
            {type: 'item', itemId: 'POKER_FACE', rarity: 'legendary', weight: 5},
            {type: 'item', itemId: 'VIP_CARD', rarity: 'legendary', weight: 4},
            {type: 'chips', chipsMin: 200_000n, chipsMax: 300_000n, rarity: 'legendary', weight: 5},
            {type: 'item', itemId: 'CHIP_FOUNTAIN', rarity: 'legendary', weight: 5},
            {type: 'item', itemId: 'GOLDEN_DICE', rarity: 'legendary', weight: 5},
            {type: 'item', itemId: 'TITLE_COLLECTOR', rarity: 'legendary', weight: 5},
        ],
    },
];

// ── Golden Box loot table (legendary only) ──

export const GOLDEN_BOX_LOOT: MysteryBoxLoot[] = [
    {type: 'item', itemId: 'VIP_CARD', rarity: 'legendary', weight: 15},
    {type: 'item', itemId: 'CHIP_FOUNTAIN', rarity: 'legendary', weight: 15},
    {type: 'item', itemId: 'GOLDEN_DICE', rarity: 'legendary', weight: 15},
    {type: 'item', itemId: 'HEIST_VAULT', rarity: 'legendary', weight: 15},
    {type: 'item', itemId: 'POKER_FACE', rarity: 'legendary', weight: 15},
    {type: 'chips', chipsMin: 200_000n, chipsMax: 500_000n, rarity: 'legendary', weight: 25},
];
