import type {ShopItem} from './types.js';

// ── Permanent Upgrades ──

export const UPGRADES: ShopItem[] = [
  {
    id: 'MISSION_SLOT_PLUS',
    name: 'ミッション枠+1',
    emoji: '📋',
    description: 'デイリーミッション枠を+1する（最大5枠）',
    price: 50_000n,
    category: 'upgrade',
    maxStack: 2,
  },
  {
    id: 'BANK_EXPANSION',
    name: '銀行拡張',
    emoji: '🏦',
    description: '銀行利率を+1%する',
    price: 60_000n,
    category: 'upgrade',
    maxStack: 3,
  },
  {
    id: 'CHIP_FOUNTAIN',
    name: 'チップの泉',
    emoji: '⛲',
    description: 'デイリーボーナス+$1,000永続',
    price: 100_000n,
    category: 'upgrade',
    maxStack: 1,
  },
  {
    id: 'VIP_CARD',
    name: 'VIPカード',
    emoji: '💎',
    description: '全ゲーム報酬+5%永続',
    price: 300_000n,
    category: 'upgrade',
    maxStack: 1,
  },
  {
    id: 'GOLDEN_DICE',
    name: 'ゴールデンダイス',
    emoji: '🎲',
    description: 'ミッション報酬+20%',
    price: 200_000n,
    category: 'upgrade',
    maxStack: 1,
  },
  {
    id: 'HEIST_VAULT',
    name: '強盗の金庫',
    emoji: '🗄️',
    description: 'Heist報酬+10%永続',
    price: 120_000n,
    category: 'upgrade',
    maxStack: 1,
  },
  {
    id: 'POKER_FACE',
    name: 'ポーカーフェイス',
    emoji: '🃏',
    description: 'ポーカー報酬+10%永続',
    price: 150_000n,
    category: 'upgrade',
    maxStack: 1,
  },
];

// ── Cosmetics ──

export const COSMETICS: ShopItem[] = [
  {
    id: 'TITLE_HIGH_ROLLER',
    name: 'ハイローラー',
    emoji: '🎰',
    description: '称号: ハイローラー',
    price: 25_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_LUCKY_STAR',
    name: 'ラッキースター',
    emoji: '⭐',
    description: '称号: ラッキースター',
    price: 25_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_CASINO_KING',
    name: 'カジノの王',
    emoji: '👑',
    description: '称号: カジノの王',
    price: 100_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_PHANTOM_THIEF',
    name: '怪盗',
    emoji: '🎭',
    description: '称号: 怪盗',
    price: 50_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_CRAFTSMAN',
    name: '職人',
    emoji: '🔨',
    description: '称号: 職人',
    price: 40_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_GENEROUS',
    name: '慈善家',
    emoji: '🤝',
    description: '称号: 慈善家',
    price: 40_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'TITLE_COLLECTOR',
    name: 'コレクター',
    emoji: '📚',
    description: '称号: コレクター',
    price: 60_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'BADGE_DIAMOND',
    name: 'ダイヤバッジ',
    emoji: '💎',
    description: 'バッジ: ダイヤモンド',
    price: 30_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'BADGE_FLAME',
    name: 'フレイムバッジ',
    emoji: '🔥',
    description: 'バッジ: フレイム',
    price: 30_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'BADGE_CROWN',
    name: 'クラウンバッジ',
    emoji: '👑',
    description: 'バッジ: クラウン',
    price: 50_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'BADGE_STAR',
    name: 'スターバッジ',
    emoji: '⭐',
    description: 'バッジ: スター',
    price: 35_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    giftable: true,
  },
  {
    id: 'BADGE_HEART',
    name: 'ハートバッジ',
    emoji: '❤️',
    description: 'バッジ: ハート',
    price: 35_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    giftable: true,
  },
];

// ── Rank-limited Cosmetics ──

export const RANK_LIMITED: ShopItem[] = [
  {
    id: 'TITLE_VIP_ELITE',
    name: 'VIPエリート',
    emoji: '🌟',
    description: '称号: VIPエリート（Gold限定）',
    price: 80_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    rankRequired: 'gold',
    giftable: true,
  },
  {
    id: 'BADGE_PLATINUM',
    name: 'プラチナバッジ',
    emoji: '💠',
    description: 'バッジ: プラチナ（Platinum限定）',
    price: 100_000n,
    category: 'cosmetic',
    cosmeticType: 'badge',
    maxStack: 1,
    rankRequired: 'platinum',
    giftable: true,
  },
  {
    id: 'TITLE_WHALE',
    name: '大富豪',
    emoji: '🐋',
    description: '称号: 大富豪（Diamond限定）',
    price: 150_000n,
    category: 'cosmetic',
    cosmeticType: 'title',
    maxStack: 1,
    rankRequired: 'diamond',
    giftable: true,
  },
];

// ── Craft-only items (not sold in shop) ──

const BUFF_DURATION_MS = 24 * 60 * 60 * 1000; // 24 hours

export const CRAFT_ITEMS: ShopItem[] = [
  {
    id: 'MEGA_XP_BOOSTER',
    name: 'メガXPブースター',
    emoji: '🧬',
    description: '24時間、XP+100%',
    price: 0n,
    category: 'craft',
    buffDurationMs: BUFF_DURATION_MS,
  },
  {
    id: 'GOLDEN_BOX',
    name: 'ゴールデンボックス',
    emoji: '🏆',
    description: '伝説確定ボックス',
    price: 0n,
    category: 'craft',
  },
  {
    id: 'SUPER_SAFETY_NET',
    name: 'スーパーセーフティ',
    emoji: '🛡️',
    description: '残高0で$10,000補填x5回',
    price: 0n,
    category: 'craft',
    maxStack: 5,
  },
  {
    id: 'MASTER_TOOL',
    name: 'マスターツール',
    emoji: '🔧',
    description: '全ジョブ報酬+10%',
    price: 0n,
    category: 'craft',
    maxStack: 1,
  },
];
