export const CasinoTheme = {
  colors: {
    gold: 0xFFD700,
    darkGreen: 0x1B5E20,
    purple: 0x7B1FA2,
    red: 0xD32F2F,
    silver: 0xC0C0C0,
    diamondBlue: 0x00BCD4,
  },
  prefixes: {
    casino: '🎰 ━━━ DIAMOND CASINO ━━━ 🎰',
    slots: '🎰 ━━━ SLOTS ━━━ 🎰',
    jackpot: '🎰 ━━━ 💥 JACKPOT!! 💥 ━━━ 🎰',
    race: '🏇 ━━━ 競馬 ━━━ 🏇',
    blackjack: '🃏 ━━━ BLACKJACK ━━━ 🃏',
    coinflip: '🪙 ━━━ COIN FLIP ━━━ 🪙',
    balance: '💰 ━━━ 残高 ━━━ 💰',
    leaderboard: '🏆 ━━━ ランキング ━━━ 🏆',
    daily: '🎁 ━━━ デイリーボーナス ━━━ 🎁',
    poker: '🃏 ━━━ POKER ━━━ 🃏',
    bank: '🏦 ━━━ BANK ━━━ 🏦',
    lottery: '🎟️ ━━━ LOTTERY ━━━ 🎟️',
    achievements: '🏅 ━━━ 実績 ━━━ 🏅',
    heist: '🔫 ━━━ HEIST ━━━ 🔫',
  },
} as const;
