import type {AchievementDefinition} from './types.js';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // Gaming
  {
    id: 'FIRST_WIN',
    name: '初勝利',
    description: '初めてゲームに勝利する',
    emoji: '🌟',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'WIN_STREAK_5',
    name: '5連勝',
    description: '直近5ゲーム全勝する',
    emoji: '🔥',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'GAMES_10',
    name: 'カジノ常連',
    description: '10回プレイする',
    emoji: '🎮',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'GAMES_100',
    name: 'ハイローラー',
    description: '100回プレイする',
    emoji: '🎲',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'GAMES_1000',
    name: 'カジノの王',
    description: '1000回プレイする',
    emoji: '👑',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'SLOTS_JACKPOT',
    name: 'ジャックポット！',
    description: 'スロットで500xを出す',
    emoji: '💎',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: true,
  },
  {
    id: 'BLACKJACK_NATURAL',
    name: 'ナチュラル21',
    description: 'ブラックジャックでナチュラルを出す',
    emoji: '🃏',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  {
    id: 'ALL_GAMES_PLAYED',
    name: 'オールラウンダー',
    description: '全ゲーム種をプレイする',
    emoji: '🎯',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: false,
  },
  // Economy
  {
    id: 'RICH_10K',
    name: '小金持ち',
    description: '残高 $10,000 以上',
    emoji: '💵',
    category: 'economy',
    contexts: ['economy_change'],
    hidden: false,
  },
  {
    id: 'RICH_100K',
    name: '富豪',
    description: '残高 $100,000 以上',
    emoji: '💰',
    category: 'economy',
    contexts: ['economy_change'],
    hidden: false,
  },
  {
    id: 'RICH_1M',
    name: 'ミリオネア',
    description: '残高 $1,000,000 以上',
    emoji: '🏆',
    category: 'economy',
    contexts: ['economy_change'],
    hidden: false,
  },
  {
    id: 'FIRST_LOAN',
    name: '借金デビュー',
    description: '初めてローンを借りる',
    emoji: '📝',
    category: 'economy',
    contexts: ['loan'],
    hidden: false,
  },
  {
    id: 'DEBT_FREE',
    name: '完済',
    description: 'ローンを全て返済する',
    emoji: '✨',
    category: 'economy',
    contexts: ['loan'],
    hidden: false,
  },
  {
    id: 'BANKRUPTCY',
    name: '破産宣告',
    description: '破産を宣告する',
    emoji: '💸',
    category: 'economy',
    contexts: ['bankruptcy'],
    hidden: false,
  },
  // Social
  {
    id: 'DAILY_STREAK_7',
    name: '皆勤賞',
    description: '7日連続でデイリーボーナスを受け取る',
    emoji: '📅',
    category: 'social',
    contexts: ['daily_claim'],
    hidden: false,
  },
  {
    id: 'DAILY_STREAK_30',
    name: '常連さん',
    description: '30日連続でデイリーボーナスを受け取る',
    emoji: '🗓️',
    category: 'social',
    contexts: ['daily_claim'],
    hidden: false,
  },
  {
    id: 'MULTIPLAYER_FIRST',
    name: '初参加',
    description: 'マルチプレイヤーゲームに初参加する',
    emoji: '🤝',
    category: 'social',
    contexts: ['multiplayer'],
    hidden: false,
  },
  // Special
  {
    id: 'BIG_WIN',
    name: '大当たり',
    description: '1回で $50,000 以上獲得する',
    emoji: '🎉',
    category: 'special',
    contexts: ['game_result'],
    hidden: true,
  },
  {
    id: 'ROCK_BOTTOM',
    name: 'どん底',
    description: '残高が $0 になる',
    emoji: '😱',
    category: 'special',
    contexts: ['economy_change'],
    hidden: true,
  },
  {
    id: 'LOTTERY_JACKPOT',
    name: '宝くじ大当たり',
    description: '宝くじで3つ全て一致させる',
    emoji: '🎟️',
    category: 'special',
    contexts: ['lottery'],
    hidden: true,
  },
  // Work
  {
    id: 'FIRST_WORK',
    name: '初出勤',
    description: '初めて働く',
    emoji: '💼',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'WORK_LEVEL_3',
    name: '中堅社員',
    description: '労働レベル3に到達する',
    emoji: '📈',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'WORK_LEVEL_5',
    name: 'カジノの重鎮',
    description: '労働レベル5に到達する',
    emoji: '🏛️',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'WORK_STREAK_5',
    name: '社畜',
    description: '労働5連勤する',
    emoji: '🔥',
    category: 'social',
    contexts: ['work'],
    hidden: false,
  },
  // Roulette
  {
    id: 'ROULETTE_STRAIGHT',
    name: '一点読み',
    description: 'ルーレットのストレートベットで勝利する',
    emoji: '🎯',
    category: 'gaming',
    contexts: ['game_result'],
    hidden: true,
  },
  // Missions
  {
    id: 'MISSION_FIRST',
    name: '初任務完了',
    description: '初めてミッションを達成する',
    emoji: '🎯',
    category: 'social',
    contexts: ['mission'],
    hidden: false,
  },
  {
    id: 'MISSION_COMPLETE_ALL',
    name: 'パーフェクト',
    description: '全ミッションを1日で達成する',
    emoji: '🏆',
    category: 'social',
    contexts: ['mission'],
    hidden: false,
  },
  // Shop
  {
    id: 'FIRST_PURCHASE',
    name: '初めてのお買い物',
    description: 'ショップで初めて購入する',
    emoji: '🛒',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'BIG_SPENDER',
    name: '大散財',
    description: 'ショップで累計$100,000使用する',
    emoji: '💸',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'MYSTERY_JACKPOT',
    name: 'ミステリージャックポット',
    description: 'ミステリーボックスから伝説アイテムを獲得する',
    emoji: '🌟',
    category: 'special',
    contexts: ['shop'],
    hidden: true,
  },
  {
    id: 'COLLECTOR',
    name: 'コレクター',
    description: '10種類以上のアイテムを所持する',
    emoji: '📚',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  // Work Mastery & Promotion
  {
    id: 'FIRST_MASTERY',
    name: '初めてのマスタリー',
    description: '熟練度Lv1に到達する',
    emoji: '🥈',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'JOB_MASTER',
    name: 'ジョブマスター',
    description: '任意ジョブで熟練度Lv5(マスター)に到達する',
    emoji: '👑',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'ALL_JOBS_MASTERED',
    name: '全職制覇',
    description: '全6ジョブでマスターに到達する',
    emoji: '🏆',
    category: 'special',
    contexts: ['work'],
    hidden: true,
  },
  {
    id: 'PROMOTED',
    name: '昇進',
    description: '昇進ジョブを初解放する',
    emoji: '⭐',
    category: 'economy',
    contexts: ['work'],
    hidden: false,
  },
  {
    id: 'WEEKLY_COMPLETE',
    name: '週間チャレンジ達人',
    description: '全ウィークリーチャレンジを完了する',
    emoji: '📋',
    category: 'social',
    contexts: ['weekly_challenge'],
    hidden: false,
  },
  // Shop — Recycle, Craft, Gift, Collection, Rank
  {
    id: 'FIRST_RECYCLE',
    name: '初リサイクル',
    description: '初めてアイテムを売却する',
    emoji: '♻️',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'FIRST_CRAFT',
    name: '初クラフト',
    description: '初めてアイテムを合成する',
    emoji: '🔨',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'FIRST_GIFT',
    name: '初ギフト',
    description: '初めてギフトを送る',
    emoji: '🎁',
    category: 'social',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'GIFT_GENEROUS',
    name: '気前よし',
    description: 'ギフトを10回送る',
    emoji: '💝',
    category: 'social',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'COLLECTION_FIRST',
    name: '初コレクション',
    description: 'コレクションを1つ完成させる',
    emoji: '📖',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'COLLECTION_MASTER',
    name: '図鑑マスター',
    description: '全コレクションを完成させる',
    emoji: '🏅',
    category: 'special',
    contexts: ['shop'],
    hidden: true,
  },
  {
    id: 'SHOP_RANK_GOLD',
    name: 'ゴールド会員',
    description: 'ショップランクGoldに到達する',
    emoji: '🥇',
    category: 'economy',
    contexts: ['shop'],
    hidden: false,
  },
  {
    id: 'SHOP_RANK_DIAMOND',
    name: 'ダイヤモンド会員',
    description: 'ショップランクDiamondに到達する',
    emoji: '💎',
    category: 'special',
    contexts: ['shop'],
    hidden: true,
  },
];
